ALTER TABLE inventory_ledger
    ALTER COLUMN quantity TYPE INTEGER,
    ALTER COLUMN unit_cost TYPE DECIMAL(10,2),
    ALTER COLUMN created_at TYPE TIMESTAMP,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
